### ISSUE TITLE
Old actions/checkout version

### ISSUE THREAD

**Issue by Theeoi** [Theeoi/notion-recurring-tasks#1]
The `deploy.yml` workflow only works with an old version of `actions/checkout`.
Using a later version gives the errors:

- ssh.ParsePrivateKey: ssh: no key found
- error copy file to dest: ***, error message: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

``` yml
# part of deploy.yml

        steps:
            - uses: actions/checkout@v1 # <-- must be v1

            - name: Copy repo content to VPS
```
