### ISSUE TITLE
Excessive usage of Coveralls

### ISSUE THREAD

**Issue by Theeoi** [Theeoi/notion-recurring-tasks#3]
The `test.yml` workflow was not executed on a previous push to the main branch. Which is understandable due to how it is written:

``` yaml
on:
    push:
        branches-ignore: [main]
    pull_request:
        branches: [main, dev]
```

The test workflow contains both pytest and coveralls which probably should be split since testing should be done on all branches but test-coverage is not strictly necessary on all branches.
